### ISSUE TITLE
BotSimple: extract interface

### ISSUE THREAD

**Issue by olenagerasimova** [g4s8/teletakes#14]
It's necessary to extract interface for `BotSimple`, now it's almost impossible to write unit tests for any class that uses it.

**Comment by olenagerasimova** [comment]
@g4s8 I've submitted PR for this, see #15

**Comment by olenagerasimova** [comment]
done

**Comment by g4s8** [comment]
@olenagerasimova thanks

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`
